apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: selenium-source-pvc
  namespace: jenkins
spec:
  storageClassName: sanitysourcestorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
