apiVersion: v1
kind: Pod
metadata:
  name: selenium-maven-pod
  labels:
    app: maven
    type: front-end
  namespace: jenkins
spec:
      containers:
      - name: selenium-server
        image: markhobson/maven-chrome:jdk-11
        workingDir: /usr/src
        command: ["mvn", "clean", "install"]
        volumeMounts:
        - name: sanity-source-vol
          mountPath: /usr/src
        - name: sanity-conf-vol
          mountPath: /root/.m2
      volumes:
       - name: sanity-source-vol
         persistentVolumeClaim:
             claimName: selenium-source-pvc
       - name: sanity-conf-vol
         persistentVolumeClaim:
             claimName: selenium-conf-pvc
      nodeSelector:
        kubernetes.io/hostname: master-node
      restartPolicy: Always
